name: GitSecretsScan

on:
  pull_request:
    branches:
      - main
      - '*.*'
    types: [opened, reopened, synchronize]

jobs:
  git-secret-check:
    name: Git Secrets Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: aws/code-editor
      - name: Git Secrets Scan Script
        run: |
          set -ex
          cd $GITHUB_WORKSPACE
          git clone https://github.com/awslabs/git-secrets.git && cd git-secrets
          sudo make install
          git secrets --register-aws --global
          cd $GITHUB_WORKSPACE/aws/code-editor
          git secrets --scan-history
